### ISSUE TITLE
Only one branch here?

### ISSUE THREAD

**Issue by ufimtsev** [brain-research/mirage-rl#1]
I wanted to see the horizon-aware V code, but it seems to be missing?

**Comment by gjtucker** [comment]
Thanks for pointing this out. I'll look into this and figure out why it didn't get pushed.

**Comment by gjtucker** [comment]
Sorry for the confusion. You have to switch to the TRPO git submodule (cd trpo) and then you can change branches. Here is the direct link: https://github.com/brain-research/mirage-rl-trpo/tree/horizon_aware_comparison.
